apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgA+WCoNwI5NFj19XiuddU9YS2WQ7Soud5vjOUkFDUBKNDj3asVnVknC1IVNnjENxJ2KbGQA9NeDH9fEEqxkox8uoB+70LTPFwdglX2pyMdzBA/4zSeaVdg6HhJSYRJhFU/N/UoC3zgfi6Q7EPsInYAbxHacbVLvvU6hnJpZSKZdwv6/gZ/4SBUDz+JmeV+WTDP3swkZkLq4K55QaWPGHzQ++q1PpnKbwvn9018+cFSs4u8dwQhAFmW5myzrJhiVADbGXH9p6t6bCudc4pv5SJozTCgoSYTQ61/Q3e/aNyMbjrMwey0KAowPQ7HyKEE4svRmhoDamK6rHcVFyuKnMgXz6LHSOPQ/RkefGMq291XHKUSHTkjpH/BSe7+9PYNi5aKxP+xb1nd1BtAFynkVTYKASyC9zCEZjsGwydOGw/f21lkOaUARIuxTlVR6+pMpI/iUbKeMi2ouxWHYEh9HtrznsIPJVpkBsRxntDhJ0Jhrv7iTpQXFQy2mSclSbsNNwJ2V3e8TLuXed4PDwkShi0rL7W2KmKHNuUpD38mOF+W6xNY+n11H/LXjUkOKrF87rbVir49wk5QevoREbmZ9AF/P/oGRgLvdDDOIBe0YMS/fe+RCfa47lYfyE9dVQ/KWAQi0wHyW5hhYhuZ4/9oyNsg1msp8SnhVGolnDHE8+Y+b8+w0dSaetmDAi1o4jxn+xgucn7OfwEonEzZ+0u/us4P7tV13/Ta93wn7
    client-secret: AgCXrXDUUyljEmvREIZLEC1QzGsOVahaf48jXUrY08ZmUur/SdIvr6sC51hasM3Q8GgaJyNeXCA+yYtimoCI+LukmlBV8aAFOIdLlHTLzvyIiFD+K3HVjr46JNd2uPUuiQWm2cPDqBzTqepF16RSjmKjYSNrf5jKmgQsh9c6jMH+4WDYhsc+yxTLOJieb0H6FEEMsUZuAa+IvW13nY5L2ZXaI24LbqQQ5n9wy8YY3Zd9L6vdcrVnrHZ7MBquA6TiLaKW5DgAQGB3weSfGilSf7+kn0I/SlzjSccDWmrEp0itHZo5ebxqen8NmYvfK7NUIIjn1W5POQud2OyeMjB5Ojc3gne7tApTaXjmRHI0aQnqtoatFUE7kIgMw5wUxKLiJQcSb5Epqu6ymBsL3SbLES60O2p+ZITQRhw1Cm3G8e2+EscIyz4pzi5Ys3Xr+gBVtK6BjOAZVHlP/aeU/eq9jI6WNREQCNabtfV9oLZeC1t31gG1HmXVJyqvU//Xh1b78MVWI5ZCFMiMH6hBNoYlCSJS6Eu2xQ6TsdHEP5Qd+Qp4WSxj3GiH3+NZRweCEKugIG7pSPhlytmaMF7qrPjHwy5aKdWTflCx0wvf8098aVJ24ZPZRsqv7wgXc3I5b7ZiuCjsI9e6ARpyEg64SaZd4EevW5jSXWh9/f0RgvUUG9UEe8Gq3pynAuM+MEw2XsCG0IZPeD+bqB7gHXZga3P/slqHmcwSbagaIvdNwXHjg8DfU0WxIE2Th/Z4
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo

