apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgAgkei/DBmWOfH7dQXOsvDgLtWVvJqI9QXjDhGUchoXuvx09gY8cNQk2BsLJ87VpxHq3y8BSDqpBOihTDigDcjGunE4aCATaWdqw5ZisRDNfQoHwYrYanF4yIXRy4qup2nVk8O476jsg0IKs/CB3L67H6PvYRRJ5cG6fpst2i7FmmYX/j5ZKEBfsQ0NlSKKI9hkU8tx1YEH6VGdjxZNJ//XCevfTOcedHWi01SdO5viAFf2NQ9Q9T4BpGpnivw5L51jz5keRuoTkPd+PCC20PG18xy4MBOXLCMR8G8FDuKcSAeGdOaKtak/eM4SctxoDSURwo6BNfhDxq4YvgCNv2H0771vOgEemMTuUvxJUtae7IaN/A4JTgJovY2/6/rBTL17GpnopHM6EMLqgMiN6lMJyCYJ9EHN/BuL2QHC3fF8bPzJblc+CgrcKJND6NBbAvs6W15Iydo4mkFYvA/xEv3HEOX3yO7o1YMDe60/qLoIarKehGhL5OeeEjsiJmBnCxBfPE3I0VpTYVmI0zOax9QExUOW72PUvgZyy0uylbCO/JLXTJEW+6ZSAL5YIOwT31HBmbrYZlACZS66/zkKVAMj35t1syIhO/2/z25XPWsfjvmggKDK+MZZysLCTDjcGx0nm4PZ4fsLn3dzyCg5b5urAbo1Zek9sHGrSN14qcIevtBZDCRQV0bOVGqHQclBMRP/jOQ1guVmO+p9J+47Z6VqqE8=
    client-secret: AgCCRzIudGGVoIDkBEQSG3QPxUqxPM1He8zdmfvmYhNERosMFlvIDMvhBYJmnhRhz5bSmYKHPiCraZVI+SFz5mBXHmwSju7jnkRkPOBu9GaRk3is/biejeOsWDgaE2brzYx5Dj32runGtaosRCLp1krGPr0vHWFntcscGPcPUKrp29uzeyBLW/7jv/xyaNGpY2wq67UAyK22QZqzJSmvHV2rpkosRw5ifqeMortKr4x4VApZp0Ql62NUNv1uJhGO6/ZySU/QHKNBCEQQyu2JHMJkHK5v33y6mDPhuhacknSMti2QXr6DTmKiMbZYsLkTiULqxlY4IPzSZkMzSGFhJ9u7uZrpK3F/NaJI4EU/B/F7QI9ctbcPzk0YU+APMNOZmlW/GvEg4A4q7SsjiTMmY1AYDKQ5Bf+/gfLJBQdI7Ftwj0xol1kS2V70nc+pFyoEfUzJ7ESS396x9UafVfagbg5lxT79vx8mQJH2EN/5ZdpcvZle/oYFwQHxxI5ZI/1aF6002eTzkEBPj3lWMoaVzz35YeVpPCwtANk1XspRPhplNpIzISZrLOzKzTIb9SO9jjMAYUT77TOHyKZ/o5n1llKfF9YSfMx3sAjbvFhOZMot2aG8a7UrUDRtsCb3YIJFo0oqMbUuU1N6gRVZ63KSmVFfrmYr+AoviCdhxm3/8qz82OP6FPv1Z6ld2uXAoqs3SzBRItaGHcPkFr/XRuNYf4xgfFWfcqrjWFYUjuS3CKfqqb7Zuuv1m3Z9
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo

