apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- certificate.yaml
- issuer.yaml
- rbc-api-mongodb.prod.yaml

patchesStrategicMerge:
- patches/deployment.rmv-debug.patch.yaml
- patches/ingress.add-tls.patch.yaml

replacements:
- path: patches/rbc-api-mongodb.replacement.yaml
