apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbc-api-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    path: core/rbc-api/overlays/staging
    repoURL: https://github.com/curioushuman/rbc-k8s.git
    targetRevision: HEAD
    kustomize:
      # https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/images/
      images:
      - curioushuman/rbc-api:latest
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

