---

apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-rbc-source
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  github:
    rbc:
      owner: curioushuman
      repository: rbc
      webhook:
        endpoint: /github-rbc
        port: "12000"
        method: POST
        url: http://argo-events.curiouscommunities.net
      events:
        - "*"
      apiToken:
        name: github-access
        key: token
      insecure: true
      active: true
      contentType: json
