---

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-rbc-sensor
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: github-rbc-source
    eventSourceName: github-rbc-source
    eventName: rbc
  triggers:
  - template:
      name: github-rbc-trigger
      k8s:
        group: ""
        version: v1
        resource: pods
        operation: create
        source:
          resource:
            apiVersion: v1
            kind: Pod
            metadata:
              generateName: github-rbc-trigger-
              labels:
                app: github-rbc-trigger
            spec:
              containers:
              - name: hello
                image: alpine
                command: ["echo"]
                args: ["This is the repo URL:\n", ""]
              restartPolicy: Never
        parameters:
          - src:
              dependencyName: github-rbc-source
              dataKey: body.repository.git_url
            dest: spec.containers.0.args.1
