apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- rbc-api-mongodb.staging.yaml

patchesStrategicMerge:
- patches/ingress.staging.patch.yaml
- patches/rbc-api.mongodb.delete.yaml

replacements:
- path: patches/rbc-api-mongodb.replacement.yaml
