apiVersion: v2
name: rbc-api
description: A Helm chart for the RbC API
type: application
version: 1.0.0
appVersion: "0.1.1"
dependencies:
  - name: rbc-lib
    repository: "file://../rbc-lib"
    version: ~0.1.15
    tags:
      - library
      - shared
  # https://artifacthub.io/packages/helm/bitnami/mongodb
  - name: mongodb
    repository: https://charts.bitnami.com/bitnami
    version: ~11.1.5
    tags:
      - database
      - mongodb
