apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-argocd
  namespace: argocd
spec:
  acme:
    email: "mike@curioushuman.com.au"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: letsencrypt-argocd-secret
    solvers:
      # Use the HTTP-01 challenge provider
      - http01:
          ingress:
            class: nginx
