apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbc-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: core/rbc-api/overlays/production
    repoURL: https://github.com/curioushuman/rbc-k8s.git
    targetRevision: HEAD
    kustomize:
      # https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/images/
      images:
      - name: curioushuman/rbc-api
        newTag: 0.1.1
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

