apiVersion: v2
name: rbc
description: An umbrella chart for the RbC ecosystem.
type: application
version: 0.3.1
dependencies:
  - name: rbc-api
    repository: "file://../subcharts/rbc-api"
    version: ~0.1.1
    tags:
      - identity
      - access
      - user
      - rbc
